### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by AstralBaby** [keatz55/phoenix_ui#27]
By any chance, is this library inspired by MUI or is it a port? Cause the documentation is a copy-paste of MUI and the components props are pretty similar if not identical.

**Comment by keatz55** [comment]
It is heavily inspired by MUI and in some cases borrow heavily from the clear/concise MUI docs. However, I'll be shifting the scope to the [ui.shadcdn.com](https://ui.shadcn.com/) model, focusing on components designed for easy copy-and-paste integration into apps.
